include(`foreach.m4')dnl
# Autogenerated by main.m4. DO NOT EDIT.
#
# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_reqs_bestpractices.html

resource "aws_dynamodb_global_table" "default" {
  count = length(var.regions) > 0 ? 1 : 0

  depends_on = [
foreach(`REGION', (REGIONS), `    aws_dynamodb_table.REGION,
')  ]

  name = var.name

  dynamic "replica" {
    for_each = toset(var.regions)

    content {
      region_name = replica.value
    }
  }
}
