# Autogenerated by tables.m4 DO NOT EDIT.

resource "aws_dynamodb_table" "ap-northeast-1" {
  count    = contains(var.regions, "ap-northeast-1") ? 1 : 0
  provider = aws.ap-northeast-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "ap-northeast-2" {
  count    = contains(var.regions, "ap-northeast-2") ? 1 : 0
  provider = aws.ap-northeast-2

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "ap-south-1" {
  count    = contains(var.regions, "ap-south-1") ? 1 : 0
  provider = aws.ap-south-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "ap-southeast-1" {
  count    = contains(var.regions, "ap-southeast-1") ? 1 : 0
  provider = aws.ap-southeast-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "ap-southeast-2" {
  count    = contains(var.regions, "ap-southeast-2") ? 1 : 0
  provider = aws.ap-southeast-2

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "ca-central-1" {
  count    = contains(var.regions, "ca-central-1") ? 1 : 0
  provider = aws.ca-central-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "eu-central-1" {
  count    = contains(var.regions, "eu-central-1") ? 1 : 0
  provider = aws.eu-central-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "eu-north-1" {
  count    = contains(var.regions, "eu-north-1") ? 1 : 0
  provider = aws.eu-north-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "eu-west-1" {
  count    = contains(var.regions, "eu-west-1") ? 1 : 0
  provider = aws.eu-west-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "eu-west-2" {
  count    = contains(var.regions, "eu-west-2") ? 1 : 0
  provider = aws.eu-west-2

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "eu-west-3" {
  count    = contains(var.regions, "eu-west-3") ? 1 : 0
  provider = aws.eu-west-3

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "sa-east-1" {
  count    = contains(var.regions, "sa-east-1") ? 1 : 0
  provider = aws.sa-east-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "us-east-1" {
  count    = contains(var.regions, "us-east-1") ? 1 : 0
  provider = aws.us-east-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "us-east-2" {
  count    = contains(var.regions, "us-east-2") ? 1 : 0
  provider = aws.us-east-2

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "us-west-1" {
  count    = contains(var.regions, "us-west-1") ? 1 : 0
  provider = aws.us-west-1

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}

resource "aws_dynamodb_table" "us-west-2" {
  count    = contains(var.regions, "us-west-2") ? 1 : 0
  provider = aws.us-west-2

  name         = var.name
  hash_key     = "username"
  billing_mode = "PAY_PER_REQUEST"

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "username"
    type = "S"
  }
}
